name             'laptop'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures laptop'
long_description 'Installs/Configures laptop'
version          '0.1.0'

depends 'ark'
depends 'dmg'
depends 'homebrew'
depends 'poise-python'
